# Generated by Django 5.1.1 on 2025-01-30 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Your current address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief bio about yourself', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.CharField(blank=True, help_text='Your current company name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_position',
            field=models.CharField(blank=True, help_text='Your current job position', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], help_text='Years of professional experience', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_profile',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text="Your professional headline, e.g. 'Senior Python Developer'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_website',
            field=models.URLField(blank=True, help_text='Your portfolio website URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, or DOCX)', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='List your key skills (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10, null=True),
        ),
    ]
