# Generated by Django 3.2.16 on 2025-03-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_user_address_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, help_text='Years of professional experience', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
