# Generated by Django 3.2.16 on 2025-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250301_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_details',
            field=models.CharField(blank=True, help_text="Details about your education (e.g., 'B.Tech in Computer Science')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'Ph.D.'), ('other', 'Other')], help_text='Your highest level of education', max_length=20, null=True),
        ),
    ]
