# Generated by Django 3.2.16 on 2025-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250301_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, help_text='Years of professional experience', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
