# Generated by Django 3.2.16 on 2025-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250301_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], help_text='Years of professional experience', max_length=20, null=True),
        ),
    ]
